on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - { os: 'macos-latest',     pkg: 'darwin-arm64' }
        - { os: 'ubuntu-24.04-arm', pkg: 'linux-aarch64' }
    steps:
    - if: startsWith(matrix.os, 'macos')
      run: |
        brew install make

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set tag or default version
      id: set_tag
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG_NAME="${GITHUB_REF#refs/tags/}"
        else
          TAG_NAME="v0.0.0"
        fi
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "::set-output name=tag::$TAG_NAME"

    - name: Build blink
      run: |
        ./configure --prefix=$PWD/dist
        gmake
        gmake install
        cp LICENSE dist

    - name: Package
      env:
        RELEASE_DIRNAME: blink-${{ env.TAG_NAME }}-${{ matrix.pkg }}
      run: |
        mv dist ${RELEASE_DIRNAME}
        tar czvf ${RELEASE_DIRNAME}.tgz ${RELEASE_DIRNAME}
        echo "RELEASE_DIRNAME=${RELEASE_DIRNAME}" >> $GITHUB_ENV

    - name: Upload build artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: blink-${{ matrix.pkg }}
        path: blink-*.tgz

  release:
    # if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        path: dist

    - name: List artifacts
      run: |
        find .

    # - name: Publish release
    #   uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
    #   with:
    #     tag_name: v${{ env.XEMU_VERSION }}
    #     name: v${{ env.XEMU_VERSION }}
    #     prerelease: false
    #     draft: false
    #     files: |
    #       dist/src.tar.gz/src.tar.gz
    #       dist/xemu-win-aarch64-debug-pdb/xemu-win-aarch64-debug.zip
    #       dist/xemu-win-aarch64-debug-pdb/xemu-win-aarch64-debug-pdb.zip
    #       dist/xemu-win-aarch64-release-pdb/xemu-win-aarch64-release.zip
    #       dist/xemu-win-aarch64-release-pdb/xemu-win-aarch64-release-pdb.zip
    #       dist/xemu-win-x86_64-debug-pdb/xemu-win-x86_64-debug.zip
    #       dist/xemu-win-x86_64-debug-pdb/xemu-win-x86_64-debug-pdb.zip
    #       dist/xemu-win-x86_64-release-pdb/xemu-win-x86_64-release.zip
    #       dist/xemu-win-x86_64-release-pdb/xemu-win-x86_64-release-pdb.zip
    #       dist/xemu-win-x86_64-release-pdb/xemu-win-release.zip
    #       dist/xemu-macos-universal-release/xemu-macos-universal-release.zip
    #       dist/xemu-macos-universal-debug/xemu-macos-universal-debug.zip
    #       dist/xemu-ubuntu-x86_64-debug/xemu/xemu-v${{ env.XEMU_VERSION }}-dbg-x86_64.AppImage
    #       dist/xemu-ubuntu-x86_64-release/xemu/xemu-v${{ env.XEMU_VERSION }}-x86_64.AppImage
    #       dist/xemu-ubuntu-aarch64-debug/xemu/xemu-v${{ env.XEMU_VERSION }}-dbg-aarch64.AppImage
    #       dist/xemu-ubuntu-aarch64-release/xemu/xemu-v${{ env.XEMU_VERSION }}-aarch64.AppImage